// REACT_APP-FIREBSE-MEASUREMEN_TID=G-W1HCR9ZVKS

/*
REACT_APP_FIREBASE_API_KEY=AIzaSyAKmQzmrLSYTW22BhtTJ0N9s2czh2zw6oA
REACT_APP_FIREBASE_AUTH_DOMAIN=genius-car-mechanics-1997e.firebaseapp.com
REACT_APP_FIREBASE_PROJECT_ID=genius-car-mechanics-1997e
REACT_APP_FIREBASE_STORAGE_BUCKET=genius-car-mechanics-1997e.appspot.com
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=995211508817
REACT_APP_FIREBASE_APP_ID=1:995211508817:web:3b8f620826cb281a034c70
*/

// apiKey: "AIzaSyBLJ-HXMJgtllIBFgnBCAYJ7H2-JTZ_wE4",
//     authDomain: "simple-firebase-authenti-60bd7.firebaseapp.com",
//     projectId: "simple-firebase-authenti-60bd7",
//     storageBucket: "simple-firebase-authenti-60bd7.appspot.com",
//     messagingSenderId: "614458015442",
//     appId: "1:614458015442:web:131c0205fb9622287bf70b"